In [ ]:
from yahoo_fin import stock_info as si
import yahoo_fin.options as ops
import yfinance as yf
from datetime import datetime
from models.black_scholes import black_scholes_call

ticker = "AAPL"

# Options Data

In [23]:
# Get call options chain for particular ticker
call_options_df = ops.get_calls(ticker=ticker)
call_options_df.head(5)

/home/anurag/Documents/repos/optionsValuationAPI/.venv/lib/python3.12/site-packages/yahoo_fin/options.py:42: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(requests.get(site, headers=headers).text)

,Contract Name,Last Trade Date (EDT),Strike,Last Price,Bid,Ask,Change,% Change,Volume,Open Interest,Implied Volatility
0,AAPL240802C00100000,8/1/2024 4:50 PM,100.0,120.28,124.55,125.05,1.25,1.05%,11,17,900.39%
1,AAPL240802C00115000,7/1/2024 2:19 PM,115.0,100.06,106.65,107.60,0.00,0.00%,4,4,0.00%
2,AAPL240802C00125000,8/1/2024 6:03 PM,125.0,93.58,99.30,100.05,0.00,0.00%,16,12,663.09%
3,AAPL240802C00135000,8/2/2024 4:03 PM,135.0,88.35,89.40,90.30,5.20,6.25%,3,10,605.08%
4,AAPL240802C00140000,8/1/2024 7:25 PM,140.0,77.84,84.45,85.25,0.00,0.00%,4,2,568.16%

In [41]:
# Get put options chain for particular ticker
ops.get_puts(ticker=ticker)

/home/anurag/Documents/repos/optionsValuationAPI/.venv/lib/python3.12/site-packages/yahoo_fin/options.py:42: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(requests.get(site, headers=headers).text)

,Contract Name,Last Trade Date (EDT),Strike,Last Price,Bid,Ask,Change,% Change,Volume,Open Interest,Implied Volatility
0,AAPL240802P00100000,6/17/2024 1:30 PM,100.0,0.02,0.00,0.00,0.00,0.00%,-,1,50.00%
1,AAPL240802P00105000,7/24/2024 1:45 PM,105.0,0.01,0.00,0.01,0.00,0.00%,1,1,437.50%
2,AAPL240802P00110000,8/2/2024 1:30 PM,110.0,0.01,0.00,0.01,0.00,0.00%,2,1,412.50%
3,AAPL240802P00115000,8/1/2024 2:45 PM,115.0,0.01,0.00,0.01,0.00,0.00%,3,673,387.50%
4,AAPL240802P00120000,7/30/2024 3:03 PM,120.0,0.01,0.00,0.01,0.00,0.00%,9,17,362.50%
5,AAPL240802P00125000,7/17/2024 1:48 PM,125.0,0.01,0.00,0.01,0.00,0.00%,-,2,343.75%
6,AAPL240802P00130000,8/1/2024 6:15 PM,130.0,0.01,0.00,0.01,0.00,0.00%,2,105,325.00%
7,AAPL240802P00135000,7/25/2024 1:30 PM,135.0,0.02,0.00,0.01,0.00,0.00%,1,372,300.00%
8,AAPL240802P00140000,7/29/2024 1:30 PM,140.0,0.02,0.00,0.01,0.00,0.00%,5,60,281.25%
9,AAPL240802P00145000,7/31/2024 2:37 PM,145.0,0.01,0.00,0.01,0.00,0.00%,1,33,262.50%
10,AAPL240802P00150000,8/1/2024 7:57 PM,150.0,0.01,0.00,0.01,0.00,0.00%,9,122,243.75%
11,AAPL240802P00155000,7/29/2024 6:36 PM,155.0,0.01,0.00,0.01,0.00,0.00%,1,575,225.00%
12,AAPL240802P00160000,8/1/2024 7:55 PM,160.0,0.01,0.00,0.01,0.00,0.00%,6,710,206.25%
13,AAPL240802P00165000,8/1/2024 7:58 PM,165.0,0.01,0.00,0.01,0.00,0.00%,94,2381,187.50%
14,AAPL240802P00170000,8/2/2024 1:30 PM,170.0,0.01,0.00,0.01,0.00,0.00%,2,2449,168.75%
15,AAPL240802P00175000,8/2/2024 1:30 PM,175.0,0.01,0.00,0.01,0.00,0.00%,28,1998,156.25%
16,AAPL240802P00180000,8/2/2024 4:39 PM,180.0,0.01,0.00,0.01,-0.01,-50.00%,36,4096,137.50%
17,AAPL240802P00185000,8/2/2024 4:26 PM,185.0,0.01,0.00,0.01,-0.03,-75.00%,145,4872,121.88%
18,AAPL240802P00190000,8/2/2024 4:23 PM,190.0,0.01,0.00,0.01,-0.06,-85.71%,371,4753,106.25%
19,AAPL240802P00195000,8/2/2024 4:36 PM,195.0,0.01,0.00,0.01,-0.10,-90.91%,1010,5861,90.63%
20,AAPL240802P00197500,8/2/2024 3:58 PM,197.5,0.01,0.00,0.01,-0.14,-93.33%,313,4188,82.81%
21,AAPL240802P00200000,8/2/2024 4:39 PM,200.0,0.01,0.00,0.01,-0.24,-96.00%,2392,22104,75.00%
22,AAPL240802P00202500,8/2/2024 4:18 PM,202.5,0.01,0.00,0.01,-0.37,-97.37%,1648,4517,68.75%
23,AAPL240802P00205000,8/2/2024 4:43 PM,205.0,0.01,0.00,0.01,-0.56,-98.25%,8577,25173,59.38%
24,AAPL240802P00207500,8/2/2024 4:42 PM,207.5,0.01,0.01,0.02,-0.91,-98.91%,4645,17077,59.38%
25,AAPL240802P00210000,8/2/2024 4:43 PM,210.0,0.02,0.01,0.02,-1.38,-99.28%,21351,21867,50.78%
26,AAPL240802P00212500,8/2/2024 4:42 PM,212.5,0.01,0.01,0.02,-2.03,-99.51%,18892,6103,44.14%
27,AAPL240802P00215000,8/2/2024 4:43 PM,215.0,0.02,0.02,0.03,-3.08,-99.35%,60704,15571,37.50%
28,AAPL240802P00217500,8/2/2024 4:44 PM,217.5,0.06,0.05,0.06,-4.03,-98.53%,60286,5736,32.03%
29,AAPL240802P00220000,8/2/2024 4:44 PM,220.0,0.15,0.15,0.15,-5.35,-97.27%,84966,11327,26.76%
30,AAPL240802P00222500,8/2/2024 4:43 PM,222.5,0.43,0.41,0.45,-6.28,-93.45%,48671,10495,21.78%
31,AAPL240802P00225000,8/2/2024 4:44 PM,225.0,1.19,1.18,1.25,-7.26,-86.02%,22096,9051,12.35%
32,AAPL240802P00227500,8/2/2024 4:43 PM,227.5,2.84,2.61,2.69,-7.56,-73.18%,3971,2741,0.00%
33,AAPL240802P00230000,8/2/2024 4:43 PM,230.0,4.75,4.85,5.05,-8.34,-63.71%,1952,8564,0.00%
34,AAPL240802P00232500,8/2/2024 4:42 PM,232.5,7.20,7.10,7.30,-7.99,-52.60%,1678,1004,0.00%
35,AAPL240802P00235000,8/2/2024 4:30 PM,235.0,10.37,9.55,9.80,-7.13,-40.74%,143,2491,0.00%
36,AAPL240802P00237500,8/2/2024 4:17 PM,237.5,14.22,11.90,12.40,-5.78,-28.90%,47,158,0.00%
37,AAPL240802P00240000,8/2/2024 4:16 PM,240.0,17.00,14.50,15.25,-5.00,-22.73%,120,111,0.00%
38,AAPL240802P00242500,8/2/2024 3:36 PM,242.5,19.45,16.60,17.35,-2.35,-10.78%,8,8,0.00%
39,AAPL240802P00245000,8/1/2024 2:29 PM,245.0,23.75,19.45,19.90,0.00,0.00%,6,1,0.00%
40,AAPL240802P00247500,7/24/2024 3:04 PM,247.5,28.60,21.60,22.35,0.00,0.00%,5,0,0.00%
41,AAPL240802P00250000,8/2/2024 3:42 PM,250.0,28.00,24.05,24.90,-4.75,-14.50%,11,11,0.00%
42,AAPL240802P00252500,7/24/2024 3:04 PM,252.5,33.59,26.85,27.45,0.00,0.00%,5,0,0.00%
43,AAPL240802P00255000,7/30/2024 1:30 PM,255.0,36.00,29.30,29.95,0.00,0.00%,2,0,0.00%
44,AAPL240802P00257500,7/25/2024 7:36 PM,257.5,38.17,31.80,32.65,0.00,0.00%,5,0,0.00%
45,AAPL240802P00260000,7/29/2024 2:04 PM,260.0,41.44,34.25,34.85,0.00,0.00%,2,0,0.00%
46,AAPL240802P00265000,7/29/2024 4:48 PM,265.0,46.30,39.30,40.10,0.00,0.00%,2,0,0.00%
47,AAPL240802P00270000,8/1/2024 5:05 PM,270.0,51.22,44.25,44.95,0.00,0.00%,3,0,0.00%

## Real-Time Stock Price

In [42]:
# Collect realtime stock price for particular ticker
stock_price_live = si.get_live_price(ticker=ticker).item()
stock_price_live

/home/anurag/Documents/repos/optionsValuationAPI/.venv/lib/python3.12/site-packages/yahoo_fin/stock_info.py:580: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  return df.close[-1]

224.27000427246094

# Data Manipulation into Output

## Options Data Formatting

In [43]:
def decimalise(x):
    """
    this function remove % string"""
    x = x.replace('%', '')
    return float(x) / 100

In [29]:
# Setup the Options Data into the results
result_df = call_options_df.loc[:, ['Contract Name', 'Strike', 'Last Price', 'Implied Volatility']]
result_df.insert(0, column='ticker', value=ticker)
result_df.rename(columns={'Contract Name': 'contract_name', 
                          'Last Price': 'premium',
                          'Strike': 'strike',
                          'Implied Volatility': 'volatility'}, inplace=True)

result_df['volatility'] = result_df['volatility'].apply(decimalise)

result_df.head(5)

  ticker        contract_name  strike  premium  volatility
0   AAPL  AAPL240802C00100000   100.0   120.28      9.0039
1   AAPL  AAPL240802C00115000   115.0   100.06      0.0000
2   AAPL  AAPL240802C00125000   125.0    93.58      6.6309
3   AAPL  AAPL240802C00135000   135.0    88.35      6.0508
4   AAPL  AAPL240802C00140000   140.0    77.84      5.6816

## Stock Data Formatting

In [44]:
result_df['stock_price'] = stock_price_live

result_df.head(5)

,ticker,contract_name,strike,premium,volatility,stock_price,interest_rate,time_to_expiry,fair_price,valuation
0,AAPL,AAPL240802C00100000,100.0,120.28,9.0039,224.270004,0.06,0.00274,125.07,Undervalued
1,AAPL,AAPL240802C00115000,115.0,100.06,0.0000,224.270004,0.06,0.00274,-1.00,N/A
2,AAPL,AAPL240802C00125000,125.0,93.58,6.6309,224.270004,0.06,0.00274,99.95,Undervalued
3,AAPL,AAPL240802C00135000,135.0,88.35,6.0508,224.270004,0.06,0.00274,90.12,Undervalued
4,AAPL,AAPL240802C00140000,140.0,77.84,5.6816,224.270004,0.06,0.00274,85.12,Undervalued

## Other Variable Formatting

In [31]:
interest_rate = 0.06 #TODO: Use API for this
result_df['interest_rate'] = interest_rate

result_df.head(5)

,ticker,contract_name,strike,premium,volatility,stock_price,interest_rate
0,AAPL,AAPL240802C00100000,100.0,120.28,9.0039,223.820404,0.06
1,AAPL,AAPL240802C00115000,115.0,100.06,0.0000,223.820404,0.06
2,AAPL,AAPL240802C00125000,125.0,93.58,6.6309,223.820404,0.06
3,AAPL,AAPL240802C00135000,135.0,88.35,6.0508,223.820404,0.06
4,AAPL,AAPL240802C00140000,140.0,77.84,5.6816,223.820404,0.06

In [32]:
# Time to Expiry Calculation
def expiry_from_contract(contract_name):
    """
    retrive expiry date from contract name"""
    n = len(ticker)
    expiry_date_string = contract_name[n:n+6]
    expiry_date = datetime.strptime(expiry_date_string, "%y%m%d")
    return expiry_date.date()

def time_to_expiry(contract_name):
    """
    Calculate number of yrs for contract"""
    today = datetime.today().date()
    expiry = expiry_from_contract(contract_name=contract_name)
    delta = expiry - today
    days = delta.days + 1
    return float(days / 365)

#time_to_expiry('AAPL24080500030000')

In [46]:
result_df['time_to_expiry'] = result_df['contract_name'].apply(time_to_expiry)

result_df.head(5)

,ticker,contract_name,strike,premium,volatility,stock_price,interest_rate,time_to_expiry,fair_price,valuation
0,AAPL,AAPL240802C00100000,100.0,120.28,9.0039,224.270004,0.06,0.00274,125.07,Undervalued
1,AAPL,AAPL240802C00115000,115.0,100.06,0.0000,224.270004,0.06,0.00274,-1.00,N/A
2,AAPL,AAPL240802C00125000,125.0,93.58,6.6309,224.270004,0.06,0.00274,99.95,Undervalued
3,AAPL,AAPL240802C00135000,135.0,88.35,6.0508,224.270004,0.06,0.00274,90.12,Undervalued
4,AAPL,AAPL240802C00140000,140.0,77.84,5.6816,224.270004,0.06,0.00274,85.12,Undervalued

## Model Calculation

In [36]:
def call_option_value(x):
    """
    Apply Model"""
    ret_val = -1
    if x['volatility'] > 0:
        ret_val = black_scholes_call(
        S=x['stock_price'],
        K=x['strike'],
        T=x['time_to_expiry'],
        r=x['interest_rate'],
        sig=x['volatility']
        )
    return round(float(ret_val),2)

In [37]:
result_df.loc[:,'fair_price'] = result_df.apply(lambda x: call_option_value(x), axis=1)

result_df.head(5)

,ticker,contract_name,strike,premium,volatility,stock_price,interest_rate,time_to_expiry,fair_price
0,AAPL,AAPL240802C00100000,100.0,120.28,9.0039,223.820404,0.06,0.00274,125.07
1,AAPL,AAPL240802C00115000,115.0,100.06,0.0000,223.820404,0.06,0.00274,-1.00
2,AAPL,AAPL240802C00125000,125.0,93.58,6.6309,223.820404,0.06,0.00274,99.95
3,AAPL,AAPL240802C00135000,135.0,88.35,6.0508,223.820404,0.06,0.00274,90.12
4,AAPL,AAPL240802C00140000,140.0,77.84,5.6816,223.820404,0.06,0.00274,85.12

In [39]:
def get_valuation(ask_price,fair_price):
    """
    Label valuations"""
    if fair_price < 0:
        return 'N/A'
    elif ask_price > fair_price:
        return 'Overvalued'
    elif ask_price < fair_price:
        return 'Undervalued'
    else:
        return 'Fair Value'

In [40]:
result_df['valuation'] = result_df.apply(lambda x: get_valuation(x['premium'], x['fair_price']), axis=1)
result_df.head(5)

,ticker,contract_name,strike,premium,volatility,stock_price,interest_rate,time_to_expiry,fair_price,valuation
0,AAPL,AAPL240802C00100000,100.0,120.28,9.0039,223.820404,0.06,0.00274,125.07,Undervalued
1,AAPL,AAPL240802C00115000,115.0,100.06,0.0000,223.820404,0.06,0.00274,-1.00,N/A
2,AAPL,AAPL240802C00125000,125.0,93.58,6.6309,223.820404,0.06,0.00274,99.95,Undervalued
3,AAPL,AAPL240802C00135000,135.0,88.35,6.0508,223.820404,0.06,0.00274,90.12,Undervalued
4,AAPL,AAPL240802C00140000,140.0,77.84,5.6816,223.820404,0.06,0.00274,85.12,Undervalued